"""Sets up allocations view

Revision ID: 25b0aad777c6
Revises: 20417701fba5
Create Date: 2020-04-14 14:55:05.800107

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25b0aad777c6'
down_revision = '20417701fba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocations_view',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_orderline', sa.String(length=255), nullable=True),
    sa.Column('batchref', sa.String(length=255), nullable=True),
    sa.Column('sku', sa.String(length=255), nullable=True),
    sa.Column('qty', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('allocations_view')
    # ### end Alembic commands ###
