"""Products boundary context

Revision ID: 9ed11becc823
Revises: 1f1add00dc3b
Create Date: 2020-04-11 15:51:55.481077

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9ed11becc823"
down_revision = "1f1add00dc3b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("sku", sa.String(length=255), nullable=False),
        sa.Column(
            "version_number", sa.Integer(), server_default="0", nullable=False
        ),
        sa.PrimaryKeyConstraint("sku"),
    )
    op.create_foreign_key(
        "fk_batches_products", "batches", "products", ["sku"], ["sku"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "batches", type_="foreignkey")
    op.drop_table("products")
    # ### end Alembic commands ###
